language: php

cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^analysis-.*$/

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
env:
  global:
    - TEST_COMMAND="composer test"

install:
    - travis_retry composer update --prefer-dist --no-interaction

script:
    - $TEST_COMMAND
